### ISSUE TITLE
Not working on Firefox in Ubuntu Linux

### ISSUE THREAD

**Issue by slocode** [klemens/ff-tst-hoverswitch#2]
Thanks for the excellent extension.  It works on the Mac version of Firefox but it's not working on Firefox in Ubuntu Linux

Ubuntu 19.10
Firefox 71.0 (64 bit)

**Comment by klemens** [comment]
Do you see any errors in the browser console? Have you tried reopening the TST sidebar?

I am using the addon myself with several different Linux distributions.

**Comment by slocode** [comment]
It’s working now.  I closed and reopened to extension and relaunched Firefox.  All is well now.  Thanks.


On Dec 22, 2019, at 5:40 AM, Klemens Schölhorn <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you see any errors in the browser console? Have you tried reopening the TST sidebar?

I am using the addon myself with several different Linux distributions.
